### ISSUE TITLE
[Iterable] Flatten array proposal

### ISSUE THREAD

**Issue by ivoreis** [jussi-kalliokoski/trine#27] opened 2015-06-16 15:54 UTC
I saw that there's no flatten generator and probably this might be useful and used by other generators.  

Example usage:
```javascript
[[1],[2]]::flatten() // yields [1,2]
```
Possible implementation in commit: 55f86ddca1ace5823368a70b881cbc8aee4847c4

**Comment by everilae** [comment] 2015-06-16 16:00
Could be made even more generic ala python's ``itertools.chain``: take an iterable of iterables (arrays, generators...) and create an iterator yielding their items sequentially. The same basic idea, but a bit more.

**Comment by jussi-kalliokoski** [comment] 2015-06-16 16:47
Duplicate of #8.

**Closed by jussi-kalliokoski** 2015-06-16 16:47 UTC
Labels: duplicate
